---
- name: Supprimer ETCD
  hosts: etcd_cluster
  become: yes

  handlers:
    - import_tasks: handlers/common.yaml
    - import_tasks: handlers/etcd.yaml

  tasks:
    - name: Desactiver service ETCD
      debug:
        msg: "Stopping etcd service"
      notify: stop etcd
      notify: disable etcd

    - name: Supprimer fichiers ETCD
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/systemd/system/etcd.service"
        - "/etc/etcd"
        - "/opt/etcd"
        - "/var/lib/etcd"
      notify: reload systemd

    - name: Remove etcd user
      ansible.builtin.user:
        name: "{{ etcd_user }}"
        state: absent

    - name: Remove etcd group
      ansible.builtin.group:
        name: "{{ etcd_group }}"
        state: absent
