---
- name: Supprimer ETCD
  hosts: etcd_cluster
  become: yes
  tasks:
    - name: Desactiver service ETCD
      debug:
        msg: "Stopping etcd service"
      notify: disable etcd

    - name: Supprimer fichiers ETCD
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/systemd/system/etcd.service"
        - "/etc/etcd"
        - "/opt/etcd"
        - "/var/lib/etcd"
      notify: reload systemd

  handlers:
    - include_tasks: handlers/common.yaml
    - include_tasks: handlers/etcd.yaml

